### ISSUE TITLE
Format of gene trees

### ISSUE THREAD

**Issue by eead-csic-compbio** [gwct/grampa#1]
Hi Gregg,
we are learning to use your software with a toy subset of our own data. We have a few questions:

1) Do the distances in input species/gene trees matter, or is just that the topology that counts?

2) We are using ML trees produced with IQTREE which are unrooted. Do you have a script to root many trees at once? We have tried both unrooted trees and also re-rooted trees with Bioperl recipes at http://bioperl.org/howtos/Trees_HOWTO.html but grampa complains with "Error 14: Couldn't find any gene trees in your gene tree input file (-g)! ". Can you please explain why this is? This how these trees look like:

(003G3788001_Sbic:0.0473523468,Os01g660101_Osat:0.0682070114,(((((((((((c41167-g5-i1_B422:0.0071088270,(((c53948-g1-i1_Barb:0.0000022034,((c64155-g1-i1_Bret:0.0036790287,(Brasy-EspV1T50461_BsyE:0.0000022034,Brasy-EspV1T50462_BsyE:0.0000022034):0.000003):0.000001,Brasy-CorV1T27273_BsyC:0.0000022034):0.000002):0.000002,c30743-g1-i1_Bpho:0.0026307689):0.000604,(Brasy-CorV1T27277_BsyC:0.0000022034,Brasy-CorV1T27278_BsyC:0.0000022034):0.001228):0.000003):0.008766,((c41167-g1-i2_B422:0.0056586685,c42288-g1-i2_Bpho:0.0051513652):0.002549,c22689-g1-i1_Barb:0.0000022615):0.005107):0.000003,((((Bradi2g249102_Bdis:0.0000022034,Bradi2g249103_Bdis:0.0000022034):0.000003,c28811-g1-i1_Bmex:0.0333430824):0.013652,c17600-g1-i1_Bd2_Bhyb:0.0014582786):0.014808,(c25963-g2-i1_Bboi:0.0213868140,((c40050-g3-i1_Bmex:0.0178642668,c20268-g8-i1_Bsta:0.0346623056):0.012839,c44330-g1-i1_Bsta:0.0000029753):0.003899):0.020011):0.012223):0.002128,c21369-g2-i1_Barb:0.0000020027):0.000003,c38485-g2-i2_Brup:0.0121306354):0.000002,Brasy-GreV1T23552_BsyG:0.0000021657):0.000002,(c34210-g1-i1_Bpin:0.0000022034,Brasy-GreV1T23551_BsyG:0.0000023960):0.000761):0.011622,c20268-g6-i1_Bsta:0.0000023651):0.053247,Brasy-GreV1T23549_BsyG:0.0000326154):0.036101,(c23686-g3-i1_Barb:0.0052990230,(c48084-g1-i1_Bpho:0.0249288511,(Brasy-CorV1T77205_BsyC:0.0000022034,Brasy-EspV1T08506_BsyE:0.0000027580):0.027264):0.029191):0.000003):0.005563,c47173-g4-i1_Bboi:0.0306583125):0.035403);

Many thanks,
Bruno

**Comment by eead-csic-compbio** [comment]
Hi again,
eventually we found out that rooted trees in ascending node order are just fine, here's the code we used to get them:

[http://bioinfoperl.blogspot.com.es/2017/07/rooting-and-laddering-newick-trees.html](http://bioinfoperl.blogspot.com.es/2017/07/rooting-and-laddering-newick-trees.html)

Cheers, Bruno

**Comment by gwct** [comment]
Hi Bruno,
Glad you were able to get it working! To answer your first question, no the branch lengths in the tree do not matter. They will be ignored since GRAMPA only uses the topology of the tree in question.

As for the ordering of the nodes, with respect to the algorithm it doesn't matter what order they are in. But there may be something in the code that requires this. I will check it out. Thanks for bringing it to my attention!

**Comment by gwct** [comment]
I am closing this issue because I was unable to replicate any problems with the ordering of nodes. If others experience problems similar to this let me know and I will re-open this issue.
