### ISSUE TITLE
multiprocessing.pool error during Step 7

### ISSUE THREAD

**Issue by angelajmcd** [gwct/grampa#3]
Hi there,

I'm trying to run grampa on a few sets of gene trees/species trees. I can run the test just fine with no error, but when I run grampa with my data I get the following error:

```
# 12.10.2020 | 12:04:09 --> STEP 7 12.04.09: Beginning reconciliations.
# 12.10.2020 | 12:04:09 --> Reconciling to MUL-tree # 0 / 691
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/amcdonnell/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "lib/mul_recon.py", line 274, in mulRecon
    gene_score = reconLCA(ginfo, sinfo, init_maps);
  File "lib/mul_recon.py", line 37, in reconLCA
    lca_maps[g].append(RT.LCA(clade_maps,sinfo)[0]);
  File "lib/recontree.py", line 160, in LCA
    if treedict[spec][2] == 'root':
KeyError: "1'"
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "grampa.py", line 218, in <module>
    grampa(start);
  File "grampa.py", line 160, in grampa
    for result in pool.imap_unordered(partial(ALG.mulRecon, gene_trees=gene_trees, v=globs.v, pickle_dir=globs.pickle_dir, nmt=num_mul_trees), mul_trees.items()):
  File "/Users/amcdonnell/anaconda3/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
KeyError: "1'"

```

I'm not sure how to correct this or troubleshoot it. Any advice?
Thanks,
Angela

**Comment by gwct** [comment]
Hi Angela,
I think this could mean that either your species tree or gene trees aren't rooted, or that they have some sort of labels that GRAMPA's tree parser can't understand.

If you want to send me examples of your trees I'd be happy to help figure it out (and code in some better error messages).
-Gregg

**Comment by angelajmcd** [comment]
Hi Gregg,

You are probably right about the labels; they're very long (and some tips have multiple "_" characters in them). I'm remaking the trees and will retry it.

**Comment by gwct** [comment]
Ok, great, let me know how that goes! Also be aware of internal node labels (like bootstrap support). Best probably just to remove those if they are causing problems since GRAMPA doesn't use them.
 
If possible, it would be great to see the trees (or a small sample of them) you were using when you encountered the error so I could try and fix it. Let me know if you'd be able to send them here or via email (greggwct@gmail.com)!
-Gregg

**Comment by angelajmcd** [comment]
Thanks! Sorry I forgot to close this issue. Your suggestions helped!
