### ISSUE TITLE
Trouble reading polytomies in gene trees?

### ISSUE THREAD

**Issue by bauber20** [gwct/grampa#4]
When providing a multi-line file containing gene trees, GRAMPA returns: 
`**Error 14: Couldn't find any gene trees in your gene tree input file (-g)! `

The trees provided are mid-point rooted and some contain collapsed nodes (polytomies)

I've traced the error to what I believe is the treeParse function as the 'grampa_trees_filtered.txt' output returns:
`# This line may not contain a tree, or if so it may be unrooted -- Filtering.`

Further parsing of outputs from other GRAMPA runs shows that only trees with polytomies are not read.

Is it known that GRAMPA cannot read these kinds of trees? And if so it I would recommend you explicitly state this as programs such as OrthoFinder will produce such trees.

Thanks for your time!

**Comment by gwct** [comment]
Hello,
You are correct that GRAMPA filters gene trees containing polytomies. The reason for this is that polytomies falsely induce extra losses in the LCA mapping algorithm. Basically for a polytomy with N branches descending, N-2 extra losses are inferred. I may be able to account for this in the future by checking for these nodes and adjusting the final loss count for the gene tree appropriately. Until then, in addition to the README and help menu stating gene trees should be bifurcating, I have specifically added text that warns that trees with polytomies will be automatically filtered.

I hope this helps, and let me know if you have any more questions!
-Gregg

**Comment by bauber20** [comment]
Excellent! That is more than understandable, and thank you for the prompt response!
