### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Dawei-Xia** [gwct/grampa#6]

**Comment by gwct** [comment]
Hello,
Sorry I was out yesterday and didn't get a chance to look at this. You've closed the issue and removed the post so can I assume you found a solution?

On my end, I was able to replicate the problem. I think it has to do with a bug I recently discovered in my tree parsing function where if one tip label's string is contained in another (e.g. "RS4" is contained within "RS42") it can't parse (see #7 for more info). In this case I was able to solve this with a bit of find and replace: I replaced the tips labeled "RS4" with "RS4a" in both the species and the gene trees. GRAMPA was able to successfully run then. 

Let me know if you have any more issues.

**Comment by Dawei-Xia** [comment]
Hi Gregg, thanks a ton for the reply. Before I knew about this bug, I tried changing the tips and it worked.

Best
Dawei
